/*
* generated by Xtext
*/
package com.ino9dev.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.ino9dev.services.LtmlGrammarAccess;

public class LtmlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LtmlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.ino9dev.parser.antlr.internal.InternalLtmlParser createParser(XtextTokenStream stream) {
		return new com.ino9dev.parser.antlr.internal.InternalLtmlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public LtmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LtmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
