/*
 * generated by Xtext
 */
package com.ino9dev.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LtmlUiModule extends com.ino9dev.ui.AbstractLtmlUiModule {
	public LtmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
