/*
 * generated by Xtext
 */
package com.ino9dev;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LtmlRuntimeModule extends com.ino9dev.AbstractLtmlRuntimeModule {

}
