/*
* generated by Xtext
*/
package com.ino9dev;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LtmlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.ino9dev.ui.internal.LtmlActivator.getInstance().getInjector("com.ino9dev.Ltml");
	}
	
}
