/*
 * generated by Xtext
 */
package com.ino9dev.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.ino9dev.ui.internal.LtmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LtmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LtmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LtmlActivator.getInstance().getInjector(LtmlActivator.COM_INO9DEV_LTML);
	}
	
}
