/*
 * generated by Xtext
 */
package com.ino9dev.ui.contentassist

import com.ino9dev.ui.contentassist.AbstractLtmlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LtmlProposalProvider extends AbstractLtmlProposalProvider {
}
