/*
 * generated by Xtext
 */
package com.ino9dev.validation

import org.eclipse.xtext.validation.Check
import com.ino9dev.ltml.Manifest
import com.ino9dev.ltml.LtmlPackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class LtmlValidator extends AbstractLtmlValidator {

    public static val INVALID_NAME = 'invalidName'

    @Check
    def checkNoManifestName(Manifest manifest) {
        if (manifest.manifestname == "") {
            warning('manifest name is not defined', LtmlPackage.Literals.MANIFEST__MANIFESTNAME,INVALID_NAME)
        }
    }

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
