/*
 * generated by Xtext
 */
package com.ino9dev.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess
import java.util.List

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class LtmlGenerator implements IGenerator {
    
    List<IGenerator> generators = newArrayList(
        new LoadTestDocumentGenerator
        ,new LoadTestImageGenerator
        ,new LoadTestJmeterTestPlanGenerator
    )

	override void doGenerate(Resource resource, IFileSystemAccess fsa) {

        //to generate load test document(by html)
        //to generate load test image        
        //to generate load test jmx file
        generators.forEach[generator
            |generator.doGenerate(resource, fsa)
        ]
    }
  }
