/*
 * generated by Xtext
 */
package com.ino9dev.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLtmlValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.ino9dev.ltml.LtmlPackage.eINSTANCE);
		return result;
	}
}
